notifications:
  email:
    recipients:
      - nacos_dev@linux.alibaba.com
      - dev-nacos@googlegroups.com
  on_success: change
  on_failure: always

language: java

jdk:
  - openjdk10
  - openjdk9
  - openjdk8

script:
  - mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true
  - mvn -Prelease-nacos clean install -U
  - mvn clean package -Pit-test
after_success:
  - mvn clean package -Pit-test
  - mvn sonar:sonar -Psonar-apache